package com.licktopia.thechampionofsudoku;

/**
 * Created by do_de on 6/20/2017.
 */

public class Tags {

    public static int[] squareTags = {com.licktopia.thechampionofsudoku.R.id.squareholder1, com.licktopia.thechampionofsudoku.R.id.squareholder2, com.licktopia.thechampionofsudoku.R.id.squareholder3, com.licktopia.thechampionofsudoku.R.id.squareholder4, com.licktopia.thechampionofsudoku.R.id.squareholder5, com.licktopia.thechampionofsudoku.R.id.squareholder6, com.licktopia.thechampionofsudoku.R.id.squareholder7, com.licktopia.thechampionofsudoku.R.id.squareholder8, com.licktopia.thechampionofsudoku.R.id.squareholder9, com.licktopia.thechampionofsudoku.R.id.squareholder10, com.licktopia.thechampionofsudoku.R.id.squareholder11
            , com.licktopia.thechampionofsudoku.R.id.squareholder12, com.licktopia.thechampionofsudoku.R.id.squareholder13, com.licktopia.thechampionofsudoku.R.id.squareholder14, com.licktopia.thechampionofsudoku.R.id.squareholder15, com.licktopia.thechampionofsudoku.R.id.squareholder16, com.licktopia.thechampionofsudoku.R.id.squareholder17, com.licktopia.thechampionofsudoku.R.id.squareholder18, com.licktopia.thechampionofsudoku.R.id.squareholder19, com.licktopia.thechampionofsudoku.R.id.squareholder20, com.licktopia.thechampionofsudoku.R.id.squareholder21, com.licktopia.thechampionofsudoku.R.id.squareholder22, com.licktopia.thechampionofsudoku.R.id.squareholder23,
            com.licktopia.thechampionofsudoku.R.id.squareholder24, com.licktopia.thechampionofsudoku.R.id.squareholder25, com.licktopia.thechampionofsudoku.R.id.squareholder26, com.licktopia.thechampionofsudoku.R.id.squareholder27, com.licktopia.thechampionofsudoku.R.id.squareholder28, com.licktopia.thechampionofsudoku.R.id.squareholder29, com.licktopia.thechampionofsudoku.R.id.squareholder30, com.licktopia.thechampionofsudoku.R.id.squareholder31, com.licktopia.thechampionofsudoku.R.id.squareholder32, com.licktopia.thechampionofsudoku.R.id.squareholder33, com.licktopia.thechampionofsudoku.R.id.squareholder34, com.licktopia.thechampionofsudoku.R.id.squareholder35,
            com.licktopia.thechampionofsudoku.R.id.squareholder36, com.licktopia.thechampionofsudoku.R.id.squareholder37, com.licktopia.thechampionofsudoku.R.id.squareholder38, com.licktopia.thechampionofsudoku.R.id.squareholder39, com.licktopia.thechampionofsudoku.R.id.squareholder40, com.licktopia.thechampionofsudoku.R.id.squareholder41, com.licktopia.thechampionofsudoku.R.id.squareholder42, com.licktopia.thechampionofsudoku.R.id.squareholder43, com.licktopia.thechampionofsudoku.R.id.squareholder44, com.licktopia.thechampionofsudoku.R.id.squareholder45, com.licktopia.thechampionofsudoku.R.id.squareholder46, com.licktopia.thechampionofsudoku.R.id.squareholder47,
            com.licktopia.thechampionofsudoku.R.id.squareholder48, com.licktopia.thechampionofsudoku.R.id.squareholder49, com.licktopia.thechampionofsudoku.R.id.squareholder50, com.licktopia.thechampionofsudoku.R.id.squareholder51, com.licktopia.thechampionofsudoku.R.id.squareholder52, com.licktopia.thechampionofsudoku.R.id.squareholder53, com.licktopia.thechampionofsudoku.R.id.squareholder54, com.licktopia.thechampionofsudoku.R.id.squareholder55, com.licktopia.thechampionofsudoku.R.id.squareholder56, com.licktopia.thechampionofsudoku.R.id.squareholder57, com.licktopia.thechampionofsudoku.R.id.squareholder58, com.licktopia.thechampionofsudoku.R.id.squareholder59,
            com.licktopia.thechampionofsudoku.R.id.squareholder60, com.licktopia.thechampionofsudoku.R.id.squareholder61, com.licktopia.thechampionofsudoku.R.id.squareholder62, com.licktopia.thechampionofsudoku.R.id.squareholder63, com.licktopia.thechampionofsudoku.R.id.squareholder64, com.licktopia.thechampionofsudoku.R.id.squareholder65, com.licktopia.thechampionofsudoku.R.id.squareholder66, com.licktopia.thechampionofsudoku.R.id.squareholder67, com.licktopia.thechampionofsudoku.R.id.squareholder68, com.licktopia.thechampionofsudoku.R.id.squareholder69, com.licktopia.thechampionofsudoku.R.id.squareholder70, com.licktopia.thechampionofsudoku.R.id.squareholder71,
            com.licktopia.thechampionofsudoku.R.id.squareholder72, com.licktopia.thechampionofsudoku.R.id.squareholder73, com.licktopia.thechampionofsudoku.R.id.squareholder74, com.licktopia.thechampionofsudoku.R.id.squareholder75, com.licktopia.thechampionofsudoku.R.id.squareholder76, com.licktopia.thechampionofsudoku.R.id.squareholder77, com.licktopia.thechampionofsudoku.R.id.squareholder78, com.licktopia.thechampionofsudoku.R.id.squareholder79, com.licktopia.thechampionofsudoku.R.id.squareholder80, com.licktopia.thechampionofsudoku.R.id.squareholder81};

    public static int[] usSquareTags = {com.licktopia.thechampionofsudoku.R.id.usersquareholder1, com.licktopia.thechampionofsudoku.R.id.usersquareholder2, com.licktopia.thechampionofsudoku.R.id.usersquareholder3, com.licktopia.thechampionofsudoku.R.id.usersquareholder4, com.licktopia.thechampionofsudoku.R.id.usersquareholder5, com.licktopia.thechampionofsudoku.R.id.usersquareholder6, com.licktopia.thechampionofsudoku.R.id.usersquareholder7, com.licktopia.thechampionofsudoku.R.id.usersquareholder8, com.licktopia.thechampionofsudoku.R.id.usersquareholder9, com.licktopia.thechampionofsudoku.R.id.usersquareholder10, com.licktopia.thechampionofsudoku.R.id.usersquareholder11
            , com.licktopia.thechampionofsudoku.R.id.usersquareholder12, com.licktopia.thechampionofsudoku.R.id.usersquareholder13, com.licktopia.thechampionofsudoku.R.id.usersquareholder14, com.licktopia.thechampionofsudoku.R.id.usersquareholder15, com.licktopia.thechampionofsudoku.R.id.usersquareholder16, com.licktopia.thechampionofsudoku.R.id.usersquareholder17, com.licktopia.thechampionofsudoku.R.id.usersquareholder18, com.licktopia.thechampionofsudoku.R.id.usersquareholder19, com.licktopia.thechampionofsudoku.R.id.usersquareholder20, com.licktopia.thechampionofsudoku.R.id.usersquareholder21, com.licktopia.thechampionofsudoku.R.id.usersquareholder22, com.licktopia.thechampionofsudoku.R.id.usersquareholder23,
            com.licktopia.thechampionofsudoku.R.id.usersquareholder24, com.licktopia.thechampionofsudoku.R.id.usersquareholder25, com.licktopia.thechampionofsudoku.R.id.usersquareholder26, com.licktopia.thechampionofsudoku.R.id.usersquareholder27, com.licktopia.thechampionofsudoku.R.id.usersquareholder28, com.licktopia.thechampionofsudoku.R.id.usersquareholder29, com.licktopia.thechampionofsudoku.R.id.usersquareholder30, com.licktopia.thechampionofsudoku.R.id.usersquareholder31, com.licktopia.thechampionofsudoku.R.id.usersquareholder32, com.licktopia.thechampionofsudoku.R.id.usersquareholder33, com.licktopia.thechampionofsudoku.R.id.usersquareholder34, com.licktopia.thechampionofsudoku.R.id.usersquareholder35,
            com.licktopia.thechampionofsudoku.R.id.usersquareholder36, com.licktopia.thechampionofsudoku.R.id.usersquareholder37, com.licktopia.thechampionofsudoku.R.id.usersquareholder38, com.licktopia.thechampionofsudoku.R.id.usersquareholder39, com.licktopia.thechampionofsudoku.R.id.usersquareholder40, com.licktopia.thechampionofsudoku.R.id.usersquareholder41, com.licktopia.thechampionofsudoku.R.id.usersquareholder42, com.licktopia.thechampionofsudoku.R.id.usersquareholder43, com.licktopia.thechampionofsudoku.R.id.usersquareholder44, com.licktopia.thechampionofsudoku.R.id.usersquareholder45, com.licktopia.thechampionofsudoku.R.id.usersquareholder46, com.licktopia.thechampionofsudoku.R.id.usersquareholder47,
            com.licktopia.thechampionofsudoku.R.id.usersquareholder48, com.licktopia.thechampionofsudoku.R.id.usersquareholder49, com.licktopia.thechampionofsudoku.R.id.usersquareholder50, com.licktopia.thechampionofsudoku.R.id.usersquareholder51, com.licktopia.thechampionofsudoku.R.id.usersquareholder52, com.licktopia.thechampionofsudoku.R.id.usersquareholder53, com.licktopia.thechampionofsudoku.R.id.usersquareholder54, com.licktopia.thechampionofsudoku.R.id.usersquareholder55, com.licktopia.thechampionofsudoku.R.id.usersquareholder56, com.licktopia.thechampionofsudoku.R.id.usersquareholder57, com.licktopia.thechampionofsudoku.R.id.usersquareholder58, com.licktopia.thechampionofsudoku.R.id.usersquareholder59,
            com.licktopia.thechampionofsudoku.R.id.usersquareholder60, com.licktopia.thechampionofsudoku.R.id.usersquareholder61, com.licktopia.thechampionofsudoku.R.id.usersquareholder62, com.licktopia.thechampionofsudoku.R.id.usersquareholder63, com.licktopia.thechampionofsudoku.R.id.usersquareholder64, com.licktopia.thechampionofsudoku.R.id.usersquareholder65, com.licktopia.thechampionofsudoku.R.id.usersquareholder66, com.licktopia.thechampionofsudoku.R.id.usersquareholder67, com.licktopia.thechampionofsudoku.R.id.usersquareholder68, com.licktopia.thechampionofsudoku.R.id.usersquareholder69, com.licktopia.thechampionofsudoku.R.id.usersquareholder70, com.licktopia.thechampionofsudoku.R.id.usersquareholder71,
            com.licktopia.thechampionofsudoku.R.id.usersquareholder72, com.licktopia.thechampionofsudoku.R.id.usersquareholder73, com.licktopia.thechampionofsudoku.R.id.usersquareholder74, com.licktopia.thechampionofsudoku.R.id.usersquareholder75, com.licktopia.thechampionofsudoku.R.id.usersquareholder76, com.licktopia.thechampionofsudoku.R.id.usersquareholder77, com.licktopia.thechampionofsudoku.R.id.usersquareholder78, com.licktopia.thechampionofsudoku.R.id.usersquareholder79, com.licktopia.thechampionofsudoku.R.id.usersquareholder80, com.licktopia.thechampionofsudoku.R.id.usersquareholder81};
    
    
    public static int[] numberImageTags = {R.drawable.blacknum_uno, R.drawable.blacknum_dos,R.drawable.blacknum_tres,R.drawable.blacknum_cuatro,R.drawable.blacknum_cinco,R.drawable.blacknum_seis,R.drawable.blacknum_siete,R.drawable.blacknum_ocho,R.drawable.blacknum_nueve};
    public static int[] lilNumTags = {R.id.lil_num1, R.id.lil_num2,R.id.lil_num3,R.id.lil_num4,R.id.lil_num5,R.id.lil_num6,R.id.lil_num7,R.id.lil_num8,R.id.lil_num9};
    public static int[] greyNumberImageTags = {R.drawable.greynum_uno, R.drawable.greynum_dos,R.drawable.greynum_tres,R.drawable.greynum_cuatro,R.drawable.greynum_cinco,R.drawable.greynum_seis,R.drawable.greynum_siete,R.drawable.greynum_ocho,R.drawable.greynum_nueve};
    public static int[] numberButtonTags = {com.licktopia.thechampionofsudoku.R.id.one, com.licktopia.thechampionofsudoku.R.id.two, com.licktopia.thechampionofsudoku.R.id.three, com.licktopia.thechampionofsudoku.R.id.four, com.licktopia.thechampionofsudoku.R.id.five, com.licktopia.thechampionofsudoku.R.id.six, com.licktopia.thechampionofsudoku.R.id.seven, com.licktopia.thechampionofsudoku.R.id.eight, com.licktopia.thechampionofsudoku.R.id.nine};
    public static int[] colorButtonTags = {R.drawable.cbut_lightgreendot, R.drawable.cbut_bluedot,R.drawable.cbut_lightreddot,R.drawable.cbut_darkreddot,R.drawable.cbut_silverdot,R.drawable.cbut_orangedot,R.drawable.cbut_purpledot,R.drawable.cbut_yellowdot,R.drawable.cbut_darkgreendot};
    public static int[] colors = {R.color.color1, R.color.color2,R.color.color3,R.color.color4,R.color.color5,R.color.color6,R.color.color7,R.color.color8,R.color.color9};
    public static int[] leaderboards = {R.string.leaderboard_fastest_time_beginner,R.string.leaderboard_fastest_time_easy,R.string.leaderboard_fastest_time_medium,R.string.leaderboard_fastest_time_hard,R.string.leaderboard_fastest_time_expert,R.string.leaderboard_fastest_time_master,R.string.leaderboard_most_total_xp,R.string.leaderboard_highest_single_game_score,R.string.leaderboard_opponents_vanquished_multiplayer};
    public static int[] achievements = {R.string.achievement_joy_giver, R.string.achievement_up_and_comer,R.string.achievement_sharp_shooter,R.string.achievement_speed_demon,R.string.achievement_big_time_scorer,R.string.achievement_up_and_comer_ii,R.string.achievement_sharp_shooter_ii,R.string.achievement_speed_demon_ii,R.string.achievement_big_time_scorer_ii,R.string.achievement_up_and_comer_iii,R.string.achievement_sharp_shooter_iii,R.string.achievement_speed_demon_iii,R.string.achievement_big_time_scorer_iii,R.string.achievement_braggart};
    public static String[] postScoreImagesColor = {
            "http://i.imgur.com/GvL6Foi.jpg","http://i.imgur.com/0DfTUBd.jpg","http://i.imgur.com/1VNzDEQ.jpg",
            "http://i.imgur.com/afTJu49.jpg","http://i.imgur.com/qs0HxtQ.jpg","http://i.imgur.com/4vQjaij.jpg",
            "http://i.imgur.com/o5GnoxB.jpg","http://i.imgur.com/lyl11zC.jpg","http://i.imgur.com/Qv9DyTl.jpg",
            "http://i.imgur.com/DljF10l.jpg","http://i.imgur.com/ZATf42I.jpg","http://i.imgur.com/8pcTvYn.jpg",
            "http://i.imgur.com/zHbnFX6.jpg","http://i.imgur.com/WO5wMLX.jpg","http://i.imgur.com/z5mlMxU.jpg",
            "http://i.imgur.com/TmgGzvA.jpg","http://i.imgur.com/EJYqW4Z.jpg","http://i.imgur.com/uFrcsIi.jpg",
            "http://i.imgur.com/WkDNOgT.jpg","http://i.imgur.com/LGtrx0S.jpg","http://i.imgur.com/fKiLkaO.jpg",
            "http://i.imgur.com/qXxMm6e.jpg","http://i.imgur.com/wb5AkHS.jpg","http://i.imgur.com/sV9n3fI.jpg",
            "http://i.imgur.com/yqO6Rwl.jpg","http://i.imgur.com/rmjQ2N2.jpg","http://i.imgur.com/SHf0mcN.jpg",
            "http://i.imgur.com/ZYOa6hO.jpg","http://i.imgur.com/5PQ1XoX.jpg","http://i.imgur.com/HF0luCQ.jpg",
            "http://i.imgur.com/bthja1M.jpg","http://i.imgur.com/aW3rwYk.jpg","http://i.imgur.com/VoIPTde.jpg",
            "http://i.imgur.com/KF12LJ8.jpg","http://i.imgur.com/yYl0dU1.jpg","http://i.imgur.com/gb2Pmw5.jpg",
            "http://i.imgur.com/s84afrN.jpg","http://i.imgur.com/thszQiI.jpg","http://i.imgur.com/rZMZIZ8.jpg",
            "http://i.imgur.com/YQ2EdqB.jpg","http://i.imgur.com/kClOmw6.jpg","http://i.imgur.com/YYYdqo8.jpg",
            "http://i.imgur.com/1j8zt18.jpg","http://i.imgur.com/U9Df3Z4.jpg","http://i.imgur.com/SXbUhrx.jpg",
            "http://i.imgur.com/IdZ4x5U.jpg","http://i.imgur.com/otKttxi.jpg","http://i.imgur.com/XWi2uPy.jpg",
            "http://i.imgur.com/Wh1eRM5.jpg","http://i.imgur.com/M2exdKg.jpg","http://i.imgur.com/4V6iT7q.jpg",
            "http://i.imgur.com/Da0d3A6.jpg"};

    public static String[] postScoreImagesNumber = {
            "http://i.imgur.com/wSont7j.jpg","http://i.imgur.com/vLzb0j7.jpg","http://i.imgur.com/qE3pYQh.jpg",
            "http://i.imgur.com/7Zo89O4.jpg","http://i.imgur.com/J39X6FI.jpg","http://i.imgur.com/udO6Gal.jpg",
            "http://i.imgur.com/x9ScYYq.jpg","http://i.imgur.com/mOoTY9c.jpg","http://i.imgur.com/y3HBy0c.jpg",
            "http://i.imgur.com/IZFbcpy.jpg","http://i.imgur.com/UVPSx5V.jpg","http://i.imgur.com/lpX7IIp.jpg",
            "http://i.imgur.com/0qAAzZf.jpg","http://i.imgur.com/vPvQF9X.jpg","http://i.imgur.com/wJXjW41.jpg",
            "http://i.imgur.com/oFdF0Cp.jpg","http://i.imgur.com/31Yj9hW.jpg","http://i.imgur.com/0UtMTIf.jpg",
            "http://i.imgur.com/uJxfdte.jpg","http://i.imgur.com/uu2Fj3E.jpg","http://i.imgur.com/GJlKPt4.jpg",
            "http://i.imgur.com/PJ7exAg.jpg","http://i.imgur.com/NDm43BL.jpg","http://i.imgur.com/lu1bhq6.jpg",
            "http://i.imgur.com/VsBFsfn.jpg","http://i.imgur.com/ursUgwB.jpg","http://i.imgur.com/51Uj6TG.jpg",
            "http://i.imgur.com/oJBsvTJ.jpg","http://i.imgur.com/zt3DCAX.jpg","http://i.imgur.com/ZcgdfB4.jpg",
            "http://i.imgur.com/p6cinxC.jpg","http://i.imgur.com/gVj0C0W.jpg","http://i.imgur.com/MveQWXV.jpg",
            "http://i.imgur.com/hR7BcQf.jpg","http://i.imgur.com/dP7IaHF.jpg","http://i.imgur.com/UMD92XB.jpg",
            "http://i.imgur.com/8CkGe0G.jpg","http://i.imgur.com/2AQZUVI.jpg","http://i.imgur.com/ekHyCqW.jpg",
            "http://i.imgur.com/rFXtlkd.jpg","http://i.imgur.com/YN8aeK5.jpg","http://i.imgur.com/YdLOFdu.jpg",
            "http://i.imgur.com/oISObRz.jpg","http://i.imgur.com/Rnu2PlI.jpg","http://i.imgur.com/gbTbb4L.jpg",
            "http://i.imgur.com/PeogfsY.jpg","http://i.imgur.com/BdR38pl.jpg","http://i.imgur.com/JVZnF73.jpg",
            "http://i.imgur.com/YBWbJxN.jpg","http://i.imgur.com/XBkQPZ2.jpg","http://i.imgur.com/4ybPj64.jpg",
            "http://i.imgur.com/phIPbJY.jpg"};

    public static String postScoreNum = "http://i.imgur.com/sRuVmHX.jpg";
    public static String postScoreCol = "http://i.imgur.com/sRuVmHX.jpg";

    public static int[] verticalBadges = {R.id.badge0,R.id.badge1,R.id.badge2,R.id.badge3,R.id.badge4,R.id.badge5,R.id.badge6,R.id.badge7,
            R.id.badge8,R.id.badge9,R.id.badge10,R.id.badge11,R.id.badge12,R.id.badge13,R.id.badge14,R.id.badge15,
            R.id.badge16,R.id.badge17,R.id.badge18,R.id.badge19,R.id.badge20,R.id.badge21,R.id.badge22,R.id.badge23,
            R.id.badge24,R.id.badge25,R.id.badge26,R.id.badge27,R.id.badge28,R.id.badge29,R.id.badge30,R.id.badge31,
            R.id.badge32,R.id.badge33,R.id.badge34,R.id.badge35,R.id.badge36,R.id.badge37,R.id.badge38,R.id.badge39,
            R.id.badge40,R.id.badge41,R.id.badge42,R.id.badge43,R.id.badge44,R.id.badge45,R.id.badge46,R.id.badge47,R.id.badge48,R.id.badge49,R.id.badge50,R.id.badge51};
    public static int[] badgeTags = {R.drawable.rank0,R.drawable.rank1,R.drawable.rank2,R.drawable.rank3,R.drawable.rank4,R.drawable.rank5,R.drawable.rank6,R.drawable.rank7,
            R.drawable.rank8,R.drawable.rank9,R.drawable.rank10,R.drawable.rank11,R.drawable.rank12,R.drawable.rank13,R.drawable.rank14,R.drawable.rank15,
            R.drawable.rank16,R.drawable.rank17,R.drawable.rank18,R.drawable.rank19,R.drawable.rank20,R.drawable.rank21,R.drawable.rank22,R.drawable.rank23,
            R.drawable.rank24,R.drawable.rank25,R.drawable.rank26,R.drawable.rank27,R.drawable.rank28,R.drawable.rank29,R.drawable.rank30,R.drawable.rank31,
            R.drawable.rank32,R.drawable.rank33,R.drawable.rank34,R.drawable.rank35,R.drawable.rank36,R.drawable.rank37,R.drawable.rank38,R.drawable.rank39,
            R.drawable.rank40,R.drawable.rank41,R.drawable.rank42,R.drawable.rank43,R.drawable.rank44,R.drawable.rank45,R.drawable.rank46,R.drawable.rank47,R.drawable.rank48,R.drawable.rank49,R.drawable.rank50,R.drawable.rank51};
    public static int[] PlayerTags = {R.id.player1,R.id.player2,R.id.player3,R.id.player4,R.id.player5,R.id.player6,R.id.player7,R.id.player8};
    public static String[] Levels = {"Beginner","Easy","Medium","Hard","Expert","Master"};
    public static int [] levelSorter = {R.id.beg, R.id.eas, R.id.med, R.id.har, R.id.exp, R.id.mas};
}
